version: '3.8'
services:
  # O serviço do Splash (já configurado)
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8050"]
    interval: 5s
    timeout: 3s
    retries: 5

  # O seu programa em Lua
  meu-app-lua:
    build: .
    depends_on:
      - splash
    environment:
      - SPLASH_URL=http://localhost:8050
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: lua ScappingClasses/AmazonScrapinClass.lua